language: C
compiler: gcc
os: linux
addons:
  apt:
    update: true
    packages:
      - valgrind
before-install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get -q update
  - sudo apt-get install -y criterion-dev
script:
  - gcc -o unittests test/tests.c src/libstring.c -lcriterion
  - valgrind --leak-check=full --error-exitcode=23 ./unittests